import { Language } from '../types';

export const content = {
  hi: {
    nav: {
      home: 'होम',
      howItWorks: 'यह कैसे काम करता है',
      forLawyers: 'वकीलों के लिए',
      chat: 'कानूनी सलाह',
      documents: 'दस्तावेज़ विश्लेषण',
      lawyers: 'वकील खोजें',
      login: 'लॉगिन / साइन अप',
    },
    hero: {
      tag: 'भारत का पहला एआई कानूनी साथी',
      title: 'अपना पर्सनल वकील, हमेशा आपके साथ',
      subtitle: 'शांत, स्पष्ट और भरोसेमंद कानूनी मार्गदर्शन। बिना किसी घबराहट के अपनी कानूनी समस्या का सही रास्ता समझें।',
      ctaPrimary: 'मुफ्त सलाह शुरू करें',
      ctaSecondary: 'प्रक्रिया समझें',
      badge: '24/7 निःशुल्क सहायता उपलब्ध',
    },
    howItWorks: {
      title: 'यह कैसे काम करता है',
      subtitle: 'केवल 3 सरल चरणों में अपनी कानूनी समस्या का समाधान पाएं',
      step1Title: 'बताएं (Describe)',
      step1Sub: 'बताओ क्या हुआ',
      step1Desc: 'अपनी समस्या को सरल भाषा या आवाज में बताएं। कोई कानूनी तकनीकी शब्द जानने की आवश्यकता नहीं है।',
      step2Title: 'विश्लेषण (Analyze)',
      step2Sub: 'कागजात समझें',
      step2Desc: 'लीगल नोटिस, एफआईआर, अनुबंध या कोई भी दस्तावेज अपलोड करें। एआई तुरंत आसान शब्दों में समझाएगा।',
      step3Title: 'मार्गदर्शन (Guide)',
      step3Sub: 'आगे का रास्ता पाएं',
      step3Desc: 'चरण-दर-चरण कार्य योजना प्राप्त करें और आवश्यकता होने पर सत्यापित वकीलों से जुड़ें।',
    },
    stats: {
      cases: '10,000+',
      casesLabel: 'मामलों में मार्गदर्शन',
      lawyers: '1,200+',
      lawyersLabel: 'सत्यापित वकील जुड़े',
      states: '28 राज्य',
      statesLabel: 'पूरे भारत में सेवा',
      languages: '3 भाषाएं',
      languagesLabel: 'हिंदी, इंग्लिश, हिंग्लिश',
    },
    platform: {
      title: 'सभी के लिए एक समाधान',
      citizenCard: {
        badge: 'आम नागरिकों के लिए',
        title: 'लोग किसी भी लीगल समस्या के लिए',
        desc: 'जमीन-जायदाद, पारिवारिक विवाद, उपभोक्ता शिकायत, एफआईआर या नौकरी से जुड़ी समस्या का शांति से समाधान पाएं।',
        cta: 'मुफ्त सलाह शुरू करें',
      },
      lawyerCard: {
        badge: 'कानूनी पेशेवरों के लिए',
        title: 'वकीलों के लिए — नए क्लाइंट्स पाएं',
        desc: 'अपने क्षेत्र के सही क्लाइंट्स से जुड़ें, पहले से तैयार केस समरी देखें और अपनी डिजिटल प्रैक्टिस बढ़ाएं।',
        cta: 'वकील के रूप में जुड़ें',
      },
    },
    disclaimer: 'यह मार्गदर्शन सिर्फ जानकारी के लिए है, प्रोफेशनल लीगल एडवाइस का रिप्लेसमेंट नहीं।',
    footer: {
      tagline: 'भारत के हर नागरिक और वकील के लिए आसान, विश्वसनीय कानूनी मार्गदर्शन।',
      quickLinks: 'त्वरित लिंक',
      legal: 'कानूनी शर्तें',
      rights: 'सर्वाधिकार सुरक्षित।',
    },
  },
  en: {
    nav: {
      home: 'Home',
      howItWorks: 'How It Works',
      forLawyers: 'For Lawyers',
      chat: 'Legal Guidance',
      documents: 'Document Analysis',
      lawyers: 'Find Lawyers',
      login: 'Login / Sign Up',
    },
    hero: {
      tag: "India's First AI Personal Legal Companion",
      title: 'Apna Personal Wakeel, Hamesha Aapke Saath',
      subtitle: 'Calm, clear, and trustworthy legal guidance. Understand your legal rights and options without stress or confusion.',
      ctaPrimary: 'Start Free Consultation',
      ctaSecondary: 'How It Works',
      badge: '24/7 Free Consultation Support',
    },
    howItWorks: {
      title: 'How It Works',
      subtitle: 'Get legal clarity in 3 simple steps',
      step1Title: 'Describe',
      step1Sub: 'Tell us what happened',
      step1Desc: 'Explain your situation in simple words or voice. No complex legal jargon required.',
      step2Title: 'Analyze',
      step2Sub: 'Understand documents',
      step2Desc: 'Upload legal notices, FIR copy, agreements or documents for instant plain-language explanation.',
      step3Title: 'Guide',
      step3Sub: 'Get your action plan',
      step3Desc: 'Receive a step-by-step guidance plan and get connected with verified specialized lawyers if needed.',
    },
    stats: {
      cases: '10,000+',
      casesLabel: 'Cases Guided',
      lawyers: '1,200+',
      lawyersLabel: 'Verified Lawyers',
      states: '28 States',
      statesLabel: 'Pan-India Coverage',
      languages: '3 Languages',
      languagesLabel: 'Hindi, English, Hinglish',
    },
    platform: {
      title: 'Designed For Everyone',
      citizenCard: {
        badge: 'For Citizens',
        title: 'Log Kisi Bhi Legal Samasya Ke Liye',
        desc: 'Get calm guidance on property, family matters, consumer disputes, FIRs, or employment issues.',
        cta: 'Start Free Consultation',
      },
      lawyerCard: {
        badge: 'For Legal Professionals',
        title: 'Wakeelon Ke Liye — Naye Clients Paayein',
        desc: 'Connect with matched clients in your jurisdiction, review AI pre-analyzed case summaries, and grow your practice.',
        cta: 'Join as a Lawyer',
      },
    },
    disclaimer: 'Ye guidance sirf jaankari ke liye hai, professional legal advice ka replacement nahi.',
    footer: {
      tagline: 'Accessible and trustworthy legal guidance for every citizen and lawyer in India.',
      quickLinks: 'Quick Links',
      legal: 'Legal',
      rights: 'All rights reserved.',
    },
  },
  hinglish: {
    nav: {
      home: 'Home',
      howItWorks: 'How It Works',
      forLawyers: 'For Lawyers',
      chat: 'Legal Guidance',
      documents: 'Document Analysis',
      lawyers: 'Find Lawyers',
      login: 'Login / Sign Up',
    },
    hero: {
      tag: 'Bharat Ka AI Legal Guidance Platform',
      title: 'Apna Personal Wakeel, Hamesha Aapke Saath',
      subtitle: 'Shanti aur spashtata ke saath kanooni salah paayein. Bina kisi ghabraahat ke apna kanooni rasta samjhein.',
      ctaPrimary: 'Start Free Consultation',
      ctaSecondary: 'How It Works',
      badge: '24/7 Free Assistance Available',
    },
    howItWorks: {
      title: 'How It Works',
      subtitle: 'Sirf 3 aasan steps mein apni legal samasya ka samadhan paayein',
      step1Title: 'Describe',
      step1Sub: 'Batao kya hua',
      step1Desc: 'Apni problem aasan bhasha ya voice mein batao. Kisi legal jargon ki zaroorat nahi hai.',
      step2Title: 'Analyze',
      step2Sub: 'Documents samjho',
      step2Desc: 'Legal notice, FIR, contract ya photo upload karo. AI turant aasan shabdo mein samjhayega.',
      step3Title: 'Guide',
      step3Sub: 'Aage ka rasta pao',
      step3Desc: 'Step-by-step action plan pao aur zaroorat padne par verified wakeelon se connect ho jao.',
    },
    stats: {
      cases: '10,000+',
      casesLabel: 'Cases Guided',
      lawyers: '1,200+',
      lawyersLabel: 'Verified Lawyers',
      states: '28 States',
      statesLabel: 'Pan-India Reach',
      languages: '3 Languages',
      languagesLabel: 'Hindi, English, Hinglish',
    },
    platform: {
      title: 'Sabhin Ke Liye Solution',
      citizenCard: {
        badge: 'Nagrikon Ke Liye',
        title: 'Log Kisi Bhi Legal Samasya Ke Liye',
        desc: 'Jameen, parivaar, consumer, FIR ya job se jude maslo par shanti se sahi rasta samjhein.',
        cta: 'Start Free Consultation',
      },
      lawyerCard: {
        badge: 'Wakeelon Ke Liye',
        title: 'Wakeelon Ke Liye — Naye Clients Paayein',
        desc: 'Apne area ke genuine clients se judein, AI case summary dekhein aur apni legal practice badhayein.',
        cta: 'Join as a Lawyer',
      },
    },
    disclaimer: 'Ye guidance sirf jaankari ke liye hai, professional legal advice ka replacement nahi.',
    footer: {
      tagline: 'Bharat ke har nagrik aur wakeel ke liye aasan, vishwasniya legal margdarshan.',
      quickLinks: 'Quick Links',
      legal: 'Legal',
      rights: 'All rights reserved.',
    },
  },
};

export function getContent(lang: Language) {
  return content[lang] || content.hi;
}
